apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: hackolak
spec:
  selector:
    app: http-echo
  ports:
    - protocol: TCP
      port: 85
      targetPort: 5678
  type: ClusterIP
