apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    argocd.argoproj.io/instance: simple-app-olak
  name: http-echo-deployment
  namespace: hackolak2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
  spec:
      containers:
        - name: http-echo-container
          image: registry.napet.dyn.nesc.nokia.net/external/utils/hashicorp/http-echo
          ports:
            - containerPort: 5678
          args:
            - "--text"
            - "Co jest grane"
