apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  spec:
      containers:
        - name: http-echo-container
          image: registry.napet.dyn.nesc.nokia.net/external/utils/hashicorp/http-echo
          ports:
            - containerPort: 5678
          args:
            - "--text"
            - "Co jest grane"
