kind: Deployment
apiVersion: apps/v1
metadata:
  name: "{{ .Release.Name }}-deploy"
  namespace: "{{ .Values.basic.namespace }}"
  labels:
    deploy: "{{ .Release.Name }}"
  annotations:
    datree.skip/DEPLOYMENT_INCORRECT_REPLICAS_VALUE: irrelevant for hackathon purposes, skipping.
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      deploy: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        deploy: "{{ .Release.Name }}"
    spec:
      containers:
        - name: ara-api
          image: "{{ .Values.deployment.ara.image }}:{{ .Values.deployment.ara.tag }}"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ARA_ALLOWED_HOSTS
              value: "{{ .Values.env.ARA_ALLOWED_HOSTS }}"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
