apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-svc"
  namespace: "{{ .Values.basic.namespace }}"
spec:
  selector:
    deploy: "{{ .Release.Name }}"
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  sessionAffinity: None
  type: "{{ .Values.service.type }}"
