apiVersion: v1
kind: Service
metadata:
  name: {{ include "cluster-preparation.fullname" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-preparation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.pod.port }}
      protocol: TCP
      name: {{ .Values.service.name }}-{{ .Release.Namespace }}-{{ .Release.Name }}
  selector:
    {{- include "cluster-preparation.selectorLabels" . | nindent 4 }}
