{{- $root := . }}
{{- $stressCount := int .Values.perf.stressCount }}
{{- range $m, $em := until $stressCount }}
{{- range $i, $ei := untilStep 1 (int $root.Values.perf.maxConfigMaps) 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lcmaas-slayer.fullname" $root }}-dir-{{ $m }}-{{ $i }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "lcmaas-slayer.labels" $root | nindent 4 }}
data:
  key0: {{ randAscii 10240 | quote }}
  key1: {{ randAscii 10240 | quote }}
  {{- if $root.Values.perf.generateKey }}
  keyS: {{ genPrivateKey "dsa" | quote }}
  {{- end }}
---
{{- end }}
{{- end }}
