apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lcmaas-slayer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lcmaas-slayer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "lcmaas-slayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lcmaas-slayer.selectorLabels" . | nindent 8 }} 
    spec:
      containers:
        - name: {{ .Values.fullnameOverride }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "{{ .Values.pod.args }}"
          ports:
            - containerPort: {{ .Values.pod.port }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.pod.port }}
            initialDelaySeconds: {{ include "lcmaas-slayer.startupTime" . }}
