{{- $root := . }}
{{- $stressCount := int .Values.perf.stressCount }}
{{- range $m, $em := until $stressCount }}
{{- range $i, $ei := untilStep 1 (int $root.Values.perf.maxSecrets) 1 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lcmaas-slayer.fullname" $root }}-secret-{{ $m }}-{{ $i }}
type: Opaque
data:
  SUPER_APP_PORT: {{ randNumeric 3 | b64enc }}
  SUPER_APP_PASSWORD: {{ randAlpha 42 | b64enc }}
  SUPER_APP_REDIS_HOST: {{ randAlpha 32 | b64enc }}
  SUPER_APP_REDIS_PORT: {{ randNumeric 4 | b64enc }}
  SUPER_APP_REDIS_PASSWORD: {{ randAlpha 64 | b64enc }}
---
{{- end }}
{{- end }}
