image:
  repository: docker-registry-remote.artifactory-espoo1.int.net.nokia.com/hashicorp/http-echo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.2.3"

imagePullSecrets: []
nameOverride: "lcmaas-slayer"
fullnameOverride: "lcmaas-slayer"

pod:
  port: 5678
  args: "-text=default"

# When test return code is set to "0" then operation "helm test <helm release>" will be "Succeeded" in another case will
# be "Failed"
test:
  returnCode: 0

schema:
  firstSchemaTestingString: correctTestStringWithoutNumbers
  secondSchemaTestingString: correctTestStringWithoutNumbers

perf:
  maxSecrets: 20
  maxConfigMaps: 20
  stressCount: 1
  generateKey: false

startupTimeSeconds: 10
