apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "prerequisite.fullname" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Release.Namespace }}/{{ .Release.Name }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service.name }}-{{ .Release.Namespace }}-{{ .Release.Name }}
            port:
              number: 5678
                          